# Linux Server list deployed in Dev Azure environment

[azure_dev_linux_servers]
vm-linux-sbx-amtest-001.monitornet.internal ansible_user=azureuser env_target=azure_dev
vm-linux-sbx-amtest-002.monitornet.internal ansible_user=azureuser env_target=azure_dev
vm-linux-sbx-amtest-003.monitornet.internal ansible_user=azureuser env_target=azure_dev